spring.application.name=backend
# Cheia secreta comuna cu Python (NU o schimba inca, o folosim pentru test!)
aeroport.security.fernet-key=AJV-_hqtc0-lxUCOROw3N879_ZXCLUM4tdwfEXf9CGk=

spring.datasource.plateform=mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB